# Generated by Django 2.0.5 on 2018-06-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0003_auto_20180531_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
