# Generated by Django 2.0.5 on 2018-06-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0004_pedido_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
    ]
