# Generated by Django 2.0.5 on 2018-06-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0005_pedido_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
