# Generated by Django 2.0.5 on 2018-06-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(default=None, max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('observacion', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.BigIntegerField(default=0)),
                ('estado_pedido', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='productos')),
                ('precio', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_app.Producto'),
        ),
    ]
