# Generated by Django 2.0.5 on 2018-06-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='logos')),
                ('productos', models.ManyToManyField(to='restaurante_app.Producto')),
            ],
        ),
    ]
